### ISSUE TITLE
Please provide a few more details on the purpose of this repo

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/qe-tools#1]
I'm sure this sounds stupid, but to me the purpose of this repo isn't clear.
Is there a reason why we cannot add the functionality provided here in the aiida-quantumespresso plugin?
I see that the qeinputparser uses aiida, so it' doesn't seem to be about avoiding to install aiida...
Which brings me back to my question ;-)

**Comment by giovannipizzi** [comment]
Here we should put anything that can run without the need to install aiida and all its dependencies.
E.g. in seek path I'm changing the code to depend on this package, but I don't want to depend on all AiiDA.

**Comment by ltalirz** [comment]
And the idea is that the aiida-quantumespresso plugin will depend on qe-tools, right?
I can update the README if you like...

**Comment by giovannipizzi** [comment]
Exactly, this should already be the case. Thanks!

**Comment by ltalirz** [comment]
Fixed in 8bf4c347a6bf73d88cff645e580fe511fdff2526
