### ISSUE TITLE
remove aiida dependencies?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/qe-tools#3]
https://github.com/aiidateam/qe-tools/blob/67df37bba60c9d1dd1e975148d8e64c73a7901de/qe_tools/parsers/pwinputparser.py#L188
https://github.com/aiidateam/qe-tools/blob/67df37bba60c9d1dd1e975148d8e64c73a7901de/qe_tools/parsers/qeinputparser.py#L235

**Comment by lekah** [comment]
The imports are inside a function that acts as a wrapper. It should be clear that this function can only be used with AiiDA being installed.  The docstring is there and indicates what the function does. 
The package as a whole does not have AiiDA dependencies, just the 2 wrapped functions.
Is it an issue?

**Comment by ltalirz** [comment]
If the idea is that aiida uses qe_tools, then why not move these functions inside aiida?

**Comment by lekah** [comment]
Because AiiDA is agnostic to qe_tools. One could move them to aiida-quantumespresso, if it's a big deal.

**Comment by lekah** [comment]
Because AiiDA is agnostic to qe_tools. One could move them to aiida-quantumespresso, if it's a big deal.
