### ISSUE TITLE
ibrav -13 is incorrect

### ISSUE THREAD

**Issue by greschd** [aiidateam/qe-tools#37]
See the following QE mailing list thread: https://www.mail-archive.com/users@lists.quantum-espresso.org/msg37950.html

Since we followed the documentation, this is bound to be wrong here. I'm not 100% sure if it's the "new" version that is incorrect or the "old" one.

**Comment by giovannipizzi** [comment]
## Commit references

- the code that does `ibrav=-13` is [here](https://gitlab.com/QEF/q-e/-/blob/3796879853239650381453fe3cdcbbbc06b3eba5/Modules/latgen.f90#L334) -> `NEW`
- `ibrav=-13` was added [here](https://gitlab.com/QEF/q-e/-/commit/c425c62af260fcb71bf157117d4f74303b4b21ca) in QE 5.1.x -> `OLD`
- [this is the commit](https://gitlab.com/QEF/q-e/-/commit/962a723a9d1e79244c8a2d7468937ab9f29982f4) that moved from the old to the new one. The first release in which it appears seems to be QE6.5.
- BTW, also `ibrav=+13` [changed over time...](https://gitlab.com/QEF/q-e/-/commit/e88508ba1e0ef2a69da2c621701c54bbe339ad4d) but this is very old (QE < 5) so I think it's ok to ignore

## Old
```fortran
     sen = sqrt( 1.d0 - celldm(5) ** 2 )
     a1(1) = 0.5d0 * celldm(1)
     a1(2) =-a1(1) * celldm(2)
     a2(1) = a1(1)
     a2(2) =-a1(2)
     a3(1) = celldm(1) * celldm(3) * celldm(5)
     a3(3) = celldm(1) * celldm(3) * sen
```

## New
```fortran
     sen = sqrt( 1.d0 - celldm(5) ** 2 )
     a1(1) = 0.5d0 * celldm(1)
     a1(2) = a1(1) * celldm(2)
     a2(1) =-a1(1)
     a2(2) = a1(2)
     a3(1) = celldm(1) * celldm(3) * celldm(5)
     a3(3) = celldm(1) * celldm(3) * sen
```
(changed signs of `a1(2)`, `a2(1)`, `a2(2)`).

**Comment by giovannipizzi** [comment]
Probably here we should do `>=6.5`?
https://github.com/aiidateam/qe-tools/blob/e3f974426605dce903f950c06274c59a552c98ed/qe_tools/parsers/qeinputparser.py#L986-L993

Also, indeed our signs seem wrong?

**Comment by greschd** [comment]
Checked also from the QE source, and I'm getting the same conclusion. Also yes, it should be ``>=6.5`` (or ``>6.4``), since it's "until 6.4.1" - I think I misinterpreted that as "before 6.4.1".
