### ISSUE TITLE
Structure of Qe/Pw/CpInputFile

### ISSUE THREAD

**Issue by greschd** [aiidateam/qe-tools#42]
Both `PwInputFile` and `CpInputFile` have the same code for parsing `namelists`, `atomic_positions`, `cell_parameters` and `atomic_species` into attributes in their `__init__`.

As far as I can tell, `QeInputFile` is just a base class and not supposed to be used directly. But then, it has `get_structure_from_qeinput` - which uses all these attributes that _aren't even defined for that class_.

I would suggest to move the following code from _both_ `PwInputFile` and `CpInputFile` into the base class:
```python
        # Parse the namelists.
        self.namelists = parse_namelists(self.input_txt)
        # Parse the ATOMIC_POSITIONS card.
        self.atomic_positions = parse_atomic_positions(self.input_txt)
        # Parse the CELL_PARAMETERS card.
        self.cell_parameters = parse_cell_parameters(self.input_txt)
        # Parse the ATOMIC_SPECIES card.
        self.atomic_species = parse_atomic_species(self.input_txt)
```

The `PwInputFile` can add its `k_points`, while `CpInputFile` is just an empty wrapper around `QeInputFile`.

The question is what to do with the structure: Can it ever be that the structure is _not_ present in an input file, or can we just add
```python
    self.structure = parse_structure(
            txt=self.input_txt,
            namelists=self.namelists,
            atomic_positions=self.atomic_positions,
            atomic_species=self.atomic_species,
            cell_parameters=self.cell_parameters,
            qe_version=self._qe_version)
    )
```
to the end of the `QeInputFile` `__init__`?

**Comment by greschd** [comment]
Hmm, the structure-related code should probably go into an intermediary (private) class (`_StructureInputFile`) - because e.g. ``pp.x`` or `pw2wannier90.x` doesn't need it in its input.

**Comment by giovannipizzi** [comment]
Indeed - maybe we leave it private. Actually, I was even thinking if we should make it an ABC?

**Comment by greschd** [comment]
If it's private, making it an `ABC` doesn't _really_ have any effect unless we add some abstract methods that each subclass should implement, no?

In any case, fine to make it private - that means we can leave the common part there, without worrying if later we don't want all that in the lowest base class.

**Comment by giovannipizzi** [comment]
Sure, ok!
I was referring mostly to this comment:
>  it has get_structure_from_qeinput - which uses all these attributes that aren't even defined for that class.

If we don't restructure, we should at least make sure those attributes are obtained from one or more functions with raise NotImplementedError or marked as an abstract method.

But any other approach is fine with me

**Comment by greschd** [comment]
Ah, I see - I think if we make it private it's easier to just put that code in the base.
