### ISSUE TITLE
When set qetools as the parser for qeinputgenerator, the generated input file for pwscf always use this setting: calculation = 'scf'.

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/qe-tools#48]
Hi,
I noted the wonderful [qeinputgenerator](https://www.materialscloud.org/work/tools/qeinputgenerator) tool belong to the materialscloud project. For this tool, when I set qetools as the parser for qeinputgenerator, the generated input file for pwscf always use this setting: calculation = 'scf'. 

As we all know, for a first-principle study on a system, the very first step should be a (vc-)relax calculation. So, I'm confused why qetools always use the `calculation = 'scf'` for the generated pwscf input file.

Regards
HY

**Comment by greschd** [comment]
As far as I can tell, that choice is unrelated to the choice of `qe-tools` - which is just used to read the supplied input file.

**Comment by sphuber** [comment]
> As we all know, for a first-principle study on a system, the very first step should be a (vc-)relax calculation

Not sure I agree with this. Perhaps you upload a structure that already has been relaxed before, or you want to intentionally compute the ground state charge density at non-equilibrium. Ultimately this is an arbitrary choice and depends on what you want to do with it. The tool on the Materials Cloud attempts to make generating the input file for Quantum ESPRESSO, when starting from just the crystal structure, easier. It can determine quite a bit of the inputs, but not everything. At the end, the Materials Cloud QE input generator simply uses the parser of `qe-tools` as one of the potential file parsers to parse the initial crystal structure definition. How it decides to present the final results has little to do with `qe-tools`.

**Comment by hongyi-zhao** [comment]
> As far as I can tell, that choice is unrelated to the choice of `qe-tools` - which is just used to read the supplied input file.

With an input file includes the following lines:
```
&CONTROL
    calculation   = "relax"
```
The qeinputgenerator with qetools as parser will give the following:

```
&CONTROL
  calculation = 'scf'
```

**Comment by hongyi-zhao** [comment]
@sphuber Thanks a lot for pointing more low-level logic of it.

**Comment by greschd** [comment]
> 
> I've tried many times and always see the following results with an input file includes the following lines:
> 
> ```
> &CONTROL
>     calculation   = "relax"
> ```
> 
> The qeinputgenerator using qetools as parser will generate corresponding setting like this:
> 
> ```
> &CONTROL
>   calculation = 'scf'
> ```

That just means `qeinputgenerator` doesn't take into account that input, even though it _is_ parsed by `qe-tools`. Just from looking at it, this input file seems to only be a way of specifying the crystal structure (with `qe-tools` being one of many parser options), so it probably doesn't make sense to implement logic based on contents only the `PWscf` file contains.

In any case, I think we can close this issue - if there is more to discuss, it's not related to `qe-tools` itself.
